modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="blockproperties"
version="${file.jarVersion}"
displayName="Block Properties"
logoFile="examplemod.png"
credits="Sarinsa (some code stuff)"
authors="FatherToast"
description='''
Yeah
'''

[[dependencies.blockproperties]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.blockproperties]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
